services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: health
      MYSQL_USER: user
      MYSQL_PASSWORD: pswd
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
volumes:
  mysql-data: